// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GFgQWs0ddWLKXU3ZE0FvRhV8R8B0Cno',
    appId: '1:852671941457:web:7c1b68e7ab91239c802170',
    messagingSenderId: '852671941457',
    projectId: 'localfoodapp-4b218',
    authDomain: 'localfoodapp-4b218.firebaseapp.com',
    storageBucket: 'localfoodapp-4b218.firebasestorage.app',
    measurementId: 'G-VLJFWM69E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ptiDjcIyRasNP9BEmpxeqOfuFLjddDM',
    appId: '1:852671941457:android:2b8a1e0952fb9b73802170',
    messagingSenderId: '852671941457',
    projectId: 'localfoodapp-4b218',
    storageBucket: 'localfoodapp-4b218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv_uEePHF_8KPBlvX4JOKYIthyh1nF8F4',
    appId: '1:852671941457:ios:846e9549540b2e18802170',
    messagingSenderId: '852671941457',
    projectId: 'localfoodapp-4b218',
    storageBucket: 'localfoodapp-4b218.firebasestorage.app',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv_uEePHF_8KPBlvX4JOKYIthyh1nF8F4',
    appId: '1:852671941457:ios:846e9549540b2e18802170',
    messagingSenderId: '852671941457',
    projectId: 'localfoodapp-4b218',
    storageBucket: 'localfoodapp-4b218.firebasestorage.app',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7GFgQWs0ddWLKXU3ZE0FvRhV8R8B0Cno',
    appId: '1:852671941457:web:25a64f81cd596784802170',
    messagingSenderId: '852671941457',
    projectId: 'localfoodapp-4b218',
    authDomain: 'localfoodapp-4b218.firebaseapp.com',
    storageBucket: 'localfoodapp-4b218.firebasestorage.app',
    measurementId: 'G-Y7MVQM11X6',
  );
}
