name: group_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  carousel_slider: ^4.2.1
  geocoding: ^2.1.1
  flutter_map: ^4.0.0
  geojson: ^1.0.0
  latlong2: ^0.8.0
  http: ^0.13.6
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/restaurants/
    - assets/data/
